services:
  frontend-server:
    image: frontend
    ports:
      - 5000:5000
  backend-server:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REQUIST_ORIGIN=http://localhost:5000
