services:

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  frontend-server:
    image: frontend
    ports:
      - 5000:5000

  backend-server:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - database

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - frontend-server
      - backend-server
