services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    privileged: true
    restart: unless-stopped
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  redis:
    image: redis
    restart: unless-stopped
  frontend-server:
    image: frontend
    container_name: frontend
    ports:
      - 5000:5000
  backend-server:
    image: backend
    container_name: backend
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost:80
    restart: unless-stopped
